In [8]:
import numpy as np
import pandas as pd

In [9]:
# Vandermonde Matrix
def col_pow_of(v,ncols,increasing=True):
    mat = np.zeros((len(v),ncols),dtype=int)
    if increasing:
        for i in range(ncols):
            mat[:,i] = v**(i)
    else:
        for i in range(ncols):
            mat[:,ncols-i-1] = v**(ncols-i-1)
    return mat
v = np.array([1,2,3,4,5])
print(col_pow_of(v,6,increasing=False))

[[   1    1    1    1    1    1]
 [   1    2    4    8   16   32]
 [   1    3    9   27   81  243]
 [   1    4   16   64  256 1024]
 [   1    5   25  125  625 3125]]


In [11]:
# Moving Average Array
def moving_avg_array(v,window_length):
    ma_array = np.zeros(len(v)-window_length+1)
    for i in range(len(ma_array)):
        ma_array[i] = np.sum(v[i:i+window_length])/window_length
    return ma_array
v = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(moving_avg_array(v,3))

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
